DROP DATABASE TODOLIST;
CREATE DATABASE TODOLIST;
USE TODOLIST;

DROP USER 'CRUD'@'%';
CREATE USER 'CRUD'@'%' IDENTIFIED BY 'Crud123123';
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'CRUD'@'%';
FLUSH PRIVILEGES;

CREATE TABLE usuarios (
idusuario INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(45),
email VARCHAR(45),
senha VARCHAR(45)
);

CREATE TABLE tarefas (
idtarefa INT AUTO_INCREMENT,
idusuario INT,
titulotarefa VARCHAR(120),
desctarefa VARCHAR(500),
statustarefa INT,

CONSTRAINT fkusuario FOREIGN KEY  (idusuario) REFERENCES usuarios(idusuario),
CONSTRAINT PRIMARY KEY (idtarefa, idusuario)

);